import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarUser from "./components/Navbar";
import HasQueryClient from "@/HasQueryClient";
import ErrorBoundary from "./components/ErrorBoundary";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AlatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HasQueryClient>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ErrorBoundary>
            <NavbarUser />
            <main>{children}</main>
            <Footer />
          </ErrorBoundary>
        </body>
      </html>
    </HasQueryClient>
  );
}
//footer bawahnya cildern
